<?php
$helper = $this->helper('Netbaseteam\Marketplace\Helper\Data');
$layout = $helper->getLandingPage();
if ($this->getRequest()->getParam('landingpage')) {
    $layout = $this->getRequest()->getParam('landingpage');
}
$allseller = $block->getAllSeller();
$hotsellers = $block->getHotsellerdata();
?>
<?php if ($layout == '1'): ?>
    <div>
        <div class="banner text-center">
            <div class="container">
                <p class="title"> Easy to Use . Pro Support . Increase Sales Volume </p>
                <h2>Welcome to Marketplace </h2>
                <p class="desc">We are largest growing community and lots of shoppers want to see what you have in store
                    <br>
                    Reach 1200 customers everyday
                </p>
                <button class="button btn-slider"><a href="<?php /* @escapeNotVerified */
                    echo $block->getUrl('customer/account/login/') ?>"><?php echo __('Open Your Shop'); ?></a>
                </button>
                <div class="author">
                    <p> Hello e-commerce world, say Hello to Marketplace </p>
                    <span>Business week</span>
                    <i class="fa fa-quote-right" aria-hidden="true"></i>
                </div>
            </div>
        </div>
        <section class="shop-land section-marketplace">
            <div class="container">
                <div class="row heading">
                    <h2>Sellers with Taste</h2>
                    <div class="rule"></div>
                </div>
                <div class="row display-clear section-content">

                    <?php if (count($hotsellers)): ?>
                        <?php foreach ($hotsellers as $seller): ?>
                            <?php $sellerId = $seller->getSellerId(); ?>
                            <?php $shopID = $seller->getShopId(); ?>
                            <?php $ratingAverage = $block->getRatingAverage($sellerId); ?>
                            <?php $ratingCount = $block->getRatingCount($sellerId); ?>
                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
                                <div class="shop-land__item">
                                    <div class="shop-land__item--bg">
                                        <img src="<?php echo $helper->getMediaUrl() . 'marketplace/' . ($seller->getShopBanner() ? $seller->getShopBanner() : 'no-images.png'); ?>"
                                             alt="bg-shop-land1">
                                    </div>
                                    <div class="shop-land__item--inner">
                                        <img src="<?php echo $helper->getMediaUrl() . 'marketplace/' . ($seller->getShopLogo() ? $seller->getShopLogo() : 'no-images.png'); ?>"
                                             alt="shop_land1">
                                        <h4><?php echo $seller->getShopTitle() ?></h4>
                                        <div class="star">
                                            <div class="rating-summary">
                                                <div title="<?php echo (int)$ratingAverage; ?>%" class="rating-result">
                                                    <span style="width:<?php echo (int)$ratingAverage; ?>%"><span><?php echo (int)$ratingAverage; ?>
                                                            %</span></span>
                                                </div>
                                            </div>
                                            <span>(<?php echo (int)$ratingCount ?> total ratings)</span>
                                        </div>
                                        <a href="<?php echo $this->getUrl("marketplace/seller/profile/shop/$shopID", ['_secure' => $this->getRequest()->isSecure()]); ?>"
                                           class="button btn-shop">View Seller</a>
                                        <a href="<?php echo $this->getUrl("marketplace/seller/profile/shop/$shopID/product/ref=page_internal/", ['_secure' => $this->getRequest()->isSecure()]); ?>"
                                           class="button btn-shop">All Product</a>

                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        </section>
        <section class="section-why section-marketplace">
            <div class="container">
                <div class="row heading">
                    <h2>why sell on us?</h2>
                    <div class="rule"></div>
                </div>
                <div class="row section-content display-clear">
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <div class="section-why__inner">
                            <img src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell1/why1.jpg'); ?>"
                                 alt="why1">
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <div class="section-why__inner section-why__bg">
                            <img src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell1/why-icon1.png'); ?>"
                                 alt="sell-us1">
                            <div class="rule"></div>
                            <div class="section-why__inner--text">
                                <h4>Simple, powerful tools</h4>
                                <p>Spend less time managing your shop and more time on the fun stuff.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <div class="section-why__inner">
                            <img src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell1/why2.jpg'); ?>"
                                 alt="why2">
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <div class="section-why__inner section-why__bg">
                            <img src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell1/why-icon2.png'); ?>"
                                 alt="sell-us1">
                            <div class="rule"></div>
                            <div class="section-why__inner--text">
                                <h4>Reach hundreds of millions customers</h4>
                                <p>We have more than 100 milion monthly unique visitor all over the world</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <div class="section-why__inner">
                            <img src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell1/why3.jpg'); ?>"
                                 alt="why3">
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <div class="section-why__inner section-why__bg		">
                            <img src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell1/why-icon3.png'); ?>"
                                 alt="sell-us1">
                            <div class="rule"></div>
                            <div class="section-why__inner--text">
                                <h4>Support and Community</h4>
                                <p>Learn how to sell successfully with our Seller and meet sellers like you by joining
                                    our</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>
        <section class="section-marketplace section-register">
            <div class="container">
                <div class="row heading">
                    <h2>Register As Seller</h2>
                    <div class="rule"></div>
                </div>
                <div class="section-content">
                    <?php
                    /**
                     * Create account form template
                     *
                     * @var $block \Magento\Customer\Block\Form\Register
                     */
                    ?>
                    <?php echo $block->getChildHtml('form_fields_before') ?>
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $block->getChildHtml('customer.form.register.extra') ?>
                    <form class="form create account form-create-account" action="<?php /* @escapeNotVerified */
                    echo $block->getUrl('marketplace/account/createpost') ?>" method="post" id="form-validate"
                          enctype="multipart/form-data"
                          autocomplete="off">
                        <fieldset class="fieldset create info">
                            <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */
                            echo $block->getSuccessUrl() ?>">
                            <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */
                            echo $block->getErrorUrl() ?>">
                            <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

                            <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
                            <?php if ($_dob->isEnabled()): ?>
                                <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
                            <?php endif ?>

                            <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
                            <?php if ($_taxvat->isEnabled()): ?>
                                <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
                            <?php endif ?>

                            <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
                            <?php if ($_gender->isEnabled()): ?>
                                <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
                            <?php endif ?>
                        </fieldset>
                        <?php if ($block->getShowAddressFields()): ?>
                            <fieldset class="fieldset address">
                                <legend class="legend"><span><?php /* @escapeNotVerified */
                                        echo __('Address Information') ?></span></legend>
                                <br>
                                <input type="hidden" name="create_address" value="1"/>

                                <div class="field company">
                                    <label for="company" class="label"><span><?php /* @escapeNotVerified */
                                            echo __('Company') ?></span></label>

                                    <div class="control">
                                        <input type="text" name="company" id="company"
                                               value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>"
                                               title="<?php /* @escapeNotVerified */
                                               echo __('Company') ?>" class="input-text <?php /* @escapeNotVerified */
                                        echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
                                    </div>
                                </div>
                                <div class="field telephone">
                                    <label for="telephone" class="label"><span><?php /* @escapeNotVerified */
                                            echo __('Phone Number') ?></span></label>

                                    <div class="control">
                                        <input type="text" name="telephone" id="telephone"
                                               value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>"
                                               title="<?php /* @escapeNotVerified */
                                               echo __('Phone Number') ?>"
                                               class="input-text <?php /* @escapeNotVerified */
                                               echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
                                    </div>
                                </div>

                                <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

                                <div class="field street required">
                                    <label for="street_1" class="label"><span><?php /* @escapeNotVerified */
                                            echo __('Street Address') ?></span></label>

                                    <div class="control">
                                        <input type="text" name="street[]"
                                               value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>"
                                               title="<?php /* @escapeNotVerified */
                                               echo __('Street Address') ?>" id="street_1"
                                               class="input-text <?php /* @escapeNotVerified */
                                               echo $_streetValidationClass ?>">

                                        <div class="nested">
                                            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                                            <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                                <div class="field additional">
                                                    <label class="label" for="street_<?php /* @escapeNotVerified */
                                                    echo $_i ?>">
													<span><?php /* @escapeNotVerified */
                                                        echo __('Address') ?></span>
                                                    </label>

                                                    <div class="control">
                                                        <input type="text" name="street[]"
                                                               value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>"
                                                               title="<?php /* @escapeNotVerified */
                                                               echo __('Street Address %1', $_i) ?>"
                                                               id="street_<?php /* @escapeNotVerified */
                                                               echo $_i ?>"
                                                               class="input-text <?php /* @escapeNotVerified */
                                                               echo $_streetValidationClass ?>">
                                                    </div>
                                                </div>
                                            <?php endfor; ?>
                                        </div>
                                    </div>
                                </div>

                                <div class="field required">
                                    <label for="city" class="label"><span><?php /* @escapeNotVerified */
                                            echo __('City') ?></span></label>

                                    <div class="control">
                                        <input type="text" name="city"
                                               value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>"
                                               title="<?php /* @escapeNotVerified */
                                               echo __('City') ?>" class="input-text <?php /* @escapeNotVerified */
                                        echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>"
                                               id="city">
                                    </div>
                                </div>

                                <div class="field region required">
                                    <label for="region_id" class="label"><span><?php /* @escapeNotVerified */
                                            echo __('State/Province') ?></span></label>

                                    <div class="control">
                                        <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */
                                        echo __('State/Province') ?>" class="validate-select" style="display:none;">
                                            <option value=""><?php /* @escapeNotVerified */
                                                echo __('Please select a region, state or province.') ?></option>
                                        </select>
                                        <input type="text" id="region" name="region"
                                               value="<?php echo $block->escapeHtml($block->getRegion()) ?>"
                                               title="<?php /* @escapeNotVerified */
                                               echo __('State/Province') ?>"
                                               class="input-text <?php /* @escapeNotVerified */
                                               echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"
                                               style="display:none;">
                                    </div>
                                </div>

                                <div class="field zip required">
                                    <label for="zip" class="label"><span><?php /* @escapeNotVerified */
                                            echo __('Zip/Postal Code') ?></span></label>

                                    <div class="control">
                                        <input type="text" name="postcode"
                                               value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>"
                                               title="<?php /* @escapeNotVerified */
                                               echo __('Zip/Postal Code') ?>" id="zip"
                                               class="input-text validate-zip-international <?php /* @escapeNotVerified */
                                               echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                                    </div>
                                </div>

                                <div class="field country required">
                                    <label for="country" class="label"><span><?php /* @escapeNotVerified */
                                            echo __('Country') ?></span></label>

                                    <div class="control">
                                        <?php echo $block->getCountryHtmlSelect() ?>
                                    </div>
                                </div>
                                <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes'); ?>
                                <?php if ($addressAttributes): ?>
                                    <?php $addressAttributes->setEntityType('customer_address'); ?>
                                    <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]'); ?>
                                    <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address'); ?>
                                    <?php echo $addressAttributes->setShowContainer(false)->toHtml() ?>
                                <?php endif; ?>
                                <input type="hidden" name="default_billing" value="1">
                                <input type="hidden" name="default_shipping" value="1">
                            </fieldset>

                        <?php endif; ?>
                        <fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
                        echo __('* Required Fields') ?>">
                            <div class="field required">
                                <label for="email_address" class="label"><span><?php /* @escapeNotVerified */
                                        echo __('Email') ?></span></label>

                                <div class="control">
                                    <input type="email" name="email" autocomplete="email" id="email_address"
                                           value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>"
                                           title="<?php /* @escapeNotVerified */
                                           echo __('Email') ?>" class="input-text"
                                           data-validate="{required:true, 'validate-email':true}">
                                </div>
                            </div>
                            <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                                <label for="password" class="label"><span><?php /* @escapeNotVerified */
                                        echo __('Password') ?></span></label>

                                <div class="control">
                                    <input type="password" name="password" id="password"
                                           title="<?php /* @escapeNotVerified */
                                           echo __('Password') ?>"
                                           class="input-text"
                                           data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                                           data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                                           data-validate="{required:true, 'validate-customer-password':true}"
                                           autocomplete="off">

                                    <div id="password-strength-meter-container" data-role="password-strength-meter">
                                        <div id="password-strength-meter" class="password-strength-meter">
                                            <?php /* @escapeNotVerified */
                                            echo __('Password Strength'); ?>:
                                            <span id="password-strength-meter-label"
                                                  data-role="password-strength-meter-label">
										<?php /* @escapeNotVerified */
                                        echo __('No Password'); ?>
									</span>
                                        </div>
                                    </div>
                                </div>

                            </div>
                            <div class="field confirmation required">
                                <label for="password-confirmation" class="label"><span><?php /* @escapeNotVerified */
                                        echo __('Confirm Password') ?></span></label>

                                <div class="control">
                                    <input type="password" name="password_confirmation"
                                           title="<?php /* @escapeNotVerified */
                                           echo __('Confirm Password') ?>" id="password-confirmation" class="input-text"
                                           data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                                </div>
                            </div>
                            <?php echo $block->getChildHtml('form_additional_info'); ?>
                            <?php if ($block->isNewsletterEnabled()): ?>
                                <div class="field choice newsletter">
                                    <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */
                                    echo __('Sign Up for Newsletter') ?>" value="1"
                                           id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?>
                                           class="checkbox">
                                    <label for="is_subscribed" class="label"><span><?php /* @escapeNotVerified */
                                            echo __('Sign Up for Newsletter') ?></span></label>
                                </div>
                                <?php /* Extensions placeholder */ ?>
                                <?php echo $block->getChildHtml('customer.form.register.newsletter') ?>
                            <?php endif ?>
                        </fieldset>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="action submit primary"
                                        title="<?php /* @escapeNotVerified */
                                        echo __('Create an Account') ?>"><span><?php /* @escapeNotVerified */
                                        echo __('Create an Account') ?></span></button>
                            </div>
                            <div class="secondary">
                                <a class="action back"
                                   href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */
                                        echo __('Back') ?></span></a>
                            </div>
                        </div>
                    </form>
                    <script>
                        require([
                            'jquery',
                            'mage/mage'
                        ], function ($) {

                            var dataForm = $('#form-validate');
                            var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

                            dataForm.mage('validation', {
                                <?php if ($_dob->isEnabled()): ?>
                                errorPlacement: function (error, element) {
                                    if (element.prop('id').search('full') !== -1) {
                                        var dobElement = $(element).parents('.customer-dob'),
                                            errorClass = error.prop('class');
                                        error.insertAfter(element.parent());
                                        dobElement.find('.validate-custom').addClass(errorClass)
                                            .after('<div class="' + errorClass + '"></div>');
                                    }
                                    else {
                                        error.insertAfter(element);
                                    }
                                },
                                ignore: ':hidden:not(' + ignore + ')'
                                <?php else: ?>
                                ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                                <?php endif ?>
                            }).find('input:text').attr('autocomplete', 'off');

                        });
                    </script>
                    <?php if ($block->getShowAddressFields()): ?>
                        <script type="text/x-magento-init">
				{
					"#country": {
						"regionUpdater": {
							"optionalRegionAllowed": <?php /* @escapeNotVerified */
                            echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
							"regionListId": "#region_id",
							"regionInputId": "#region",
							"postcodeId": "#zip",
							"form": "#form-validate",
							"regionJson": <?php /* @escapeNotVerified */
                            echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
							"defaultRegion": "<?php /* @escapeNotVerified */
                            echo $block->getFormData()->getRegionId() ?>",
							"countriesWithOptionalZip": <?php /* @escapeNotVerified */
                            echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
						}
					}
				}



                        </script>
                    <?php endif; ?>
                </div>
            </div>
        </section>
        <section class="section-recommend section-marketplace">
            <div class="container">
                <div class="row heading">
                    <h2>Why do more sellers
                        <a href="#">recommend</a>
                        <span>
					<i class="fa fa-star one"></i>
					<i class="fa fa-star two"></i>
					<i class="fa fa-star three"></i>
				</span>
                        Marketplace than any other marketplace?</h2>
                    <p>We've spent years listening to our sellers. Their entrepreneurial spirit inspires us to work
                        harder and build smarter. The result is a marketplace that lets you hit the ground running and
                        scale quickly. It probably doesn't hurt that you can save 50% in fees vs. our competitors. </p>
                </div>
                <div class="row section-content display-clear">
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor1.png'); ?>"
                                        alt="vendor1"></a>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor2.png'); ?>"
                                        alt="vendor2"></a>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor3.png'); ?>"
                                        alt="vendor3"></a>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor4.png'); ?>"
                                        alt="vendor4"></a>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor5.png'); ?>"
                                        alt="vendor5"></a>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor6.png'); ?>"
                                        alt="vendor6"></a>
                        </div>
                    </div>
                </div>
                <div class="row display-clear">
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor1.png'); ?>"
                                        alt="vendor1"></a>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor2.png'); ?>"
                                        alt="vendor2"></a>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor3.png'); ?>"
                                        alt="vendor3"></a>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor4.png'); ?>"
                                        alt="vendor4"></a>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor5.png'); ?>"
                                        alt="vendor5"></a>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-2 col-lg-2">
                        <div class="section-recommend__inner">
                            <a href="#" class="display-flex"><img
                                        src="<?php echo $this->getViewFileUrl('Netbaseteam_Marketplace::images/marketplace-sell3/vendor6.png'); ?>"
                                        alt="vendor6"></a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="section-marketplace section-ready">
            <div class="container">
                <div class="row heading">
                    <h2>Ready to start selling?</h2>
                    <div class="rule"></div>
                    <p>With no monthly membership costs and low fees, selling on our marketplace is a low risk way to
                        start your online business. Start selling to day.</p>
                    <button class="button btn-slider"><a href="<?php /* @escapeNotVerified */
                        echo $block->getUrl('customer/account/login/') ?>"><?php echo __('Open Your Shop'); ?></a>
                    </button>
                </div>
            </div>
        </section>
    </div>
<?php endif; ?>