<?php
  $helper = $this->helper('Netbaseteam\Marketplace\Helper\Data');
?>
<div class="right_col" role="main">
  <div>
    <div class="page-title">
      <div class="title_left">
        <h3>Transactions <small>Agreement between buyer and seller</small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Default Grid <small>Transactions</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <?=$this->getChildHtml();?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "admin_vendor": {}
        }
    }
</script>