var config = {
    map: {
        '*': {
            netbaseteamTreeview: 'Netbaseteam_Marketplace/js/treeview/jquery.treeview',
            productGallery:     'Netbaseteam_Marketplace/js/product-gallery',
            baseImage:          'Netbaseteam_Marketplace/catalog/base-image-uploader',
            newOptionDialog:  'Netbaseteam_Marketplace/js/new-option-dialog',
            openOptionModal:  'Netbaseteam_Marketplace/js/option-modal',
            newAttributeDialog:  'Netbaseteam_Marketplace/js/new-attribute-dialog',
            openAttributeModal:  'Netbaseteam_Marketplace/js/attribute-modal',
            newGroupedProductDialog:  'Netbaseteam_Marketplace/js/new-grouped-product-dialog',
            openGroupedProductDialog:  'Netbaseteam_Marketplace/js/grouped-product-modal',
            newRelatedProductDialog:  'Netbaseteam_Marketplace/js/new-related-product-dialog',
            openRelatedProductDialog:  'Netbaseteam_Marketplace/js/related-product-modal',
            newUpsellProductDialog:  'Netbaseteam_Marketplace/js/new-upsell-product-dialog',
            openUpsellProductDialog:  'Netbaseteam_Marketplace/js/upsell-product-modal',
            newCrosssellProductDialog:  'Netbaseteam_Marketplace/js/new-crosssell-product-dialog',
            openCrosssellProductDialog:  'Netbaseteam_Marketplace/js/crosssell-product-modal',
            newVideoDialog:  'Netbaseteam_Marketplace/js/new-video-dialog',
            openVideoModal:  'Netbaseteam_Marketplace/js/video-modal',
            productEditForm: 'Netbaseteam_Marketplace/js/product-edit-form',
            sellerProfile: 'Netbaseteam_Marketplace/js/seller-profile',
            sellerEditProfile: 'Netbaseteam_Marketplace/js/seller-edit-profile',
            relatedProduct: 'Netbaseteam_Marketplace/js/product/related-product',
            upsellProduct: 'Netbaseteam_Marketplace/js/product/upsell-product',
            crosssellProduct: 'Netbaseteam_Marketplace/js/product/crosssell-product',
            productAttribute: 'Netbaseteam_Marketplace/catalog/product/attribute',
            productAttributes:  'Netbaseteam_Marketplace/catalog/product-attributes',
            configurableAttribute:  'Netbaseteam_Marketplace/catalog/product/configurable-attribute',
            notification : 'Netbaseteam_Marketplace/js/notification',
            owlCarousel: 'Netbaseteam_Marketplace/js/owl.carousel.min',
            vacationInfo: 'Netbaseteam_Marketplace/js/vacation-info',
            textillate: 'Netbaseteam_Marketplace/js/lib/textillate/jquery.textillate',
            timecircles: 'Netbaseteam_Marketplace/js/lib/timecircles/TimeCircles',
            sellerLocator: 'Netbaseteam_Marketplace/js/plugin/locator/locator',
            locator_init:'Netbaseteam_Marketplace/js/plugin/locator/locator_init',
            locator_creator : 'Netbaseteam_Marketplace/js/plugin/locator/locator_creator',
            locator_map : 'Netbaseteam_Marketplace/js/plugin/locator/map',
            chartJs : 'Netbaseteam_Marketplace/vendors/Chart.js/Chart.min',
            dateJs : 'Netbaseteam_Marketplace/vendors/DateJS/build/date',
            bootstrap : 'Netbaseteam_Marketplace/vendors/bootstrap/js/bootstrap.min',
            bootstrap_daterangepicker : 'Netbaseteam_Marketplace/vendors/bootstrap-daterangepicker/daterangepicker',
            datatables : 'Netbaseteam_Marketplace/vendors/datatables/jquery.dataTables.min',
            flot : 'Netbaseteam_Marketplace/vendors/flot/jquery.flot',
            flotPie : 'Netbaseteam_Marketplace/vendors/flot/jquery.flot',
            flotResize : 'Netbaseteam_Marketplace/vendors/flot/jquery.flot.resize',
            flotStack : 'Netbaseteam_Marketplace/vendors/flot/jquery.flot.stack',
            flotTime : 'Netbaseteam_Marketplace/vendors/flot/jquery.flot.time',
            flotSpline : 'Netbaseteam_Marketplace/vendors/flot-spline/js/jquery.flot.spline.min',
            flotCurvedlines : 'Netbaseteam_Marketplace/vendors/flot.curvedlines/curvedLines',
            flotOrderbars : 'Netbaseteam_Marketplace/vendors/flot.orderbars/jquery.flot.orderBars',
            sparkline : 'Netbaseteam_Marketplace/vendors/jquery-sparkline/jquery.sparkline.min',
            moment : 'Netbaseteam_Marketplace/vendors/moment/min/moment.min',
            admin_vendor : 'Netbaseteam_Marketplace/build/js/admin_vendor.min',
            Js_Default:'Netbaseteam_Marketplace/js/page/default',
            reloadGrid: 'Netbaseteam_Marketplace/js/grid/component-reloader',
            collapsable: 'Netbaseteam_Marketplace/js/collapsable'
        }
    },
    shim: {
        "newAttributeDialog": ["jquery"],
        "newOptionDialog": ["jquery"],
        "newVideoDialog": ["jquery"],
        "netbaseteamTreeview": ["jquery"],
        "owlCarousel": ["jquery"],
        "textillate": ["jquery"],
        "timecircles": ["jquery"],
        "sellerLocator": ["jquery"],
        "localtor_init": ["jquery"],
        "localtor_creator": ["jquery"],
        "locator_map": ["jquery"],
        "googleMapNote": ["jquery"]
    }

};