<?php

// @codingStandardsIgnoreFile
$_attributes = $block->getListAttributes();
?>

<?php echo $block->getChildHtml('info');?>

<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>List Attributes <small>Confirms your product attributes</small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Default Grid <small>Attributes</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>

          <div class="x_content">
            <table id="datatable" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Id</th>
                  <th>Attribute Label</th>
                  <th>Attribute Code</th>
                </tr>
              </thead>

              <tbody>
                <?php if ($_attributes && count($_attributes)): ?>
                    <?php foreach ($_attributes as $_attributes): ?>
                        <?php $attributeDetail = $this->getListAttributesDetails($_attributes->getAttributeId());?>
                        <tr>
                          <td><?php echo $_attributes->getAttributeId() ?></td>
                          <td><?php echo isset($attributeDetail->getData()[0]['frontend_label']) ? $attributeDetail->getData()[0]['frontend_label'] : '' ?></td>
                          <td><?php echo $_attributes->getAttributeCode()?></td>
                        </tr>
                    <?php endforeach;?>    
                <?php endif ?>
              </tbody>
            </table>
            <?php if ($block->getPagerHtml()): ?>
              <?php echo $block->getPagerHtml();?>
            <?php endif; ?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "admin_vendor": {}
        }
    }
</script>