<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$helper = $this->helper('Netbaseteam\Marketplace\Helper\Data');
?>
<?php if ($block->isPossibleOnepageCheckout()):?>
    <button type="button"
            data-role="proceed-to-checkout"
            title="<?= /* @escapeNotVerified */ __('Checkout Everything') ?>"
            data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"}}'
            class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
            <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
        <span><?= /* @escapeNotVerified */ __('Checkout Everything') ?></span>
    </button>
    <button <?php echo (!$helper->isLoggedIn() ? "disable='disable'" : ""); ?> type="button"
            style="margin: 21px 0px"
            id="checkout-selected-btn"
            data-role="proceed-to-checkout-select"
            title="<?= /* @escapeNotVerified */ __('Checkout Select') ?>"
            class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
            <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>
            data-post='{"action":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>","data":{"productIds":""}}'>
        <span><?= /* @escapeNotVerified */ __('Checkout Select') ?></span>
    </button>
    <?php if (!$helper->isLoggedIn()) : ?>
        <span style="color: red"><?php echo __('Please sign in to use the feature'); ?></span>
    <?php endif?>
<?php endif?>