<?php
  $helper = $this->helper('Netbaseteam\Marketplace\Helper\Data');
?>
<div class="right_col" role="main">
  <div>
    <div class="page-actions-buttons <?php echo ((!$helper->checkDataEmailToLimitFunction() || !$helper->releaseLimit()) ? 'add-new-product' : '')?>">
        <form action="<?php echo $block->getUrl('marketplace/product/new', ['_secure' => $this->getRequest()->isSecure()]) ?>"
              method="post">
            <div id="add_new_product" title="Add Product" class="actions-split">
                <button class="action submit primary" id="add_new_product-button" title="Add Product" type="submit">
                    <span>Add Product</span>
                </button>
                <div class="input-box netbaseteam-type-product">
                    <label><?php echo __('Type') ?>:</label>
                    <select name="type" class="required-entry">
                        <?php foreach ($this->getAllowedProductTypes() as $type) { ?>
                            <option value="<?php echo $type['value'] ?>"><?php echo $type['label'] ?></option>
                        <?php } ?>
                    </select>
                </div>
                <div>
                    <label><?php echo __('Attribute Set') ?>:</label>
                    <div class="input-box netbaseteam-type-product">
                        <select name="set" class="required-entry">
                            <?php if (count($this->getAllowedSets())): ?>
                                <?php foreach ($this->getAllowedSets() as $set) { ?>
                                    <option value="<?php echo $set['value'] ?>"><?php echo $set['label'] ?></option>
                                <?php } ?>
                            <?php endif; ?>
                        </select>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="page-title">
      <div class="title_left">
        <h3>Manages Product <small>All products on your store</small></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Default Grid <small>Products</small></h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li>
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <?=$this->getChildHtml();?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "admin_vendor": {}
        }
    }
</script>